services:
  app1:
    image: anandhurkrishna/cicd-demo:latest
    container_name: cicd-app-1
    restart: always
    mem_limit: 512m
    cpus: 0.5

  app2:
    image: anandhurkrishna/cicd-demo:latest
    container_name: cicd-app-2
    restart: always
    mem_limit: 512m
    cpus: 0.5

  nginx:
    image: nginx:latest
    container_name: cicd-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
    restart: always
